<?php

namespace Database\Seeders;

use App\Models\AboutCouncilMember;
use Illuminate\Database\Seeder;

class AboutCouncilMemberSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            0 => [
                'id' => 1,
                'about_id' => 1,
                'name' => 'Hon. MARIA PILAR T. ADLAON',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Health, Social Services, Women & Children',
                'image' => '1788604797_organization-council-member-1.png',
                'display_order' => 8,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 10:42:04',
            ],
            1 => [
                'id' => 2,
                'about_id' => 1,
                'name' => 'Hon. MAJIN V. ANDAK',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Agriculture, Appropriations, DRR',
                'image' => '1788607321_organization-council-member-2.png',
                'display_order' => 3,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 11:22:01',
            ],
            2 => [
                'id' => 3,
                'about_id' => 1,
                'name' => 'Hon. ANAM H. DAMMANG',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Peace & Order, Energy',
                'image' => '1788607446_organization-council-member-3.png',
                'display_order' => 2,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 11:24:06',
            ],
            3 => [
                'id' => 4,
                'about_id' => 1,
                'name' => 'Hon. ALVIN D. HASSAN',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Land Use, Transportation, Ways & Means',
                'image' => '1788607321_organization-council-member-4.png',
                'display_order' => 4,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 11:22:01',
            ],
            4 => [
                'id' => 5,
                'about_id' => 1,
                'name' => 'Hon. REY T. OMAMALIN',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Education, Public Works, Tourism',
                'image' => '1788607321_organization-council-member-5.png',
                'display_order' => 5,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 11:22:01',
            ],
            5 => [
                'id' => 6,
                'about_id' => 1,
                'name' => 'Hon. JULHISAN H. BUHALI',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Environment',
                'image' => '1788605170_organization-council-member-6.png',
                'display_order' => 6,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 10:46:10',
            ],
            6 => [
                'id' => 7,
                'about_id' => 1,
                'name' => 'Hon. ABUBAKHAR S. ANJAWANG',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Games & Amusement, Good Governance',
                'image' => '1788605037_organization-council-member-7.png',
                'display_order' => 7,
                'created_at' => '2026-08-04 02:23:30',
                'updated_at' => '2026-09-05 10:43:57',
            ],
            7 => [
                'id' => 15,
                'about_id' => 1,
                'name' => 'Hon. DARIO S. ALFORQUE',
                'role' => 'Council Member',
                'category' => 'sangguniang_bayan',
                'area_of_expertise' => 'Trade & Commerce, Market',
                'image' => '1788607446_organization-council-member-8.png',
                'display_order' => 1,
                'created_at' => '2026-08-04 02:52:38',
                'updated_at' => '2026-09-05 11:24:06',
            ],
            8 => [
                'id' => 17,
                'about_id' => 1,
                'name' => 'CRISTINA R. OMAMALIN',
                'role' => 'Secretary to the Sanggunian',
                'category' => 'secretary',
                'area_of_expertise' => 'Legislative Administration',
                'image' => '1788603359_organization-council-member-9.png',
                'display_order' => 1,
                'created_at' => '2026-09-05 10:15:59',
                'updated_at' => '2026-09-05 10:15:59',
            ],
            9 => [
                'id' => 18,
                'about_id' => 1,
                'name' => 'Hon. SAMMA G. DAUD',
                'role' => 'Council Member',
                'category' => 'ex_officio',
                'area_of_expertise' => 'Municipal Indigenous Peoples Mandatory Representative (IPMR)',
                'image' => '1788603359_organization-council-member-10.png',
                'display_order' => 3,
                'created_at' => '2026-09-05 10:15:59',
                'updated_at' => '2026-09-05 10:15:59',
            ],
            10 => [
                'id' => 20,
                'about_id' => 1,
                'name' => 'Hon. ALEX C. FIGUEROA',
                'role' => 'Council Member',
                'category' => 'ex_officio',
                'area_of_expertise' => 'Liga ng mga Barangay President',
                'image' => '1788604128_organization-council-member-11.png',
                'display_order' => 2,
                'created_at' => '2026-09-05 10:28:48',
                'updated_at' => '2026-09-05 10:28:48',
            ],
            11 => [
                'id' => 21,
                'about_id' => 1,
                'name' => 'Hon. KAYL NIKKO A. CALOÑGE',
                'role' => 'SK President',
                'category' => 'ex_officio',
                'area_of_expertise' => 'Sangguniang Kabataan President',
                'image' => '1788604128_organization-council-member-12.png',
                'display_order' => 1,
                'created_at' => '2026-09-05 10:28:48',
                'updated_at' => '2026-09-05 10:31:30',
            ],
        ];

        AboutCouncilMember::query()->upsert($rows, ['id']);
    }
}
