<?php

namespace Database\Seeders;

use App\Models\About;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class AboutSeeder extends Seeder
{
    public function run(): void
    {
        $barangays = $this->runBarangaySeedData();

        $about = About::query()->updateOrCreate(
            ['id' => 1],
            [
                'page_key' => 'about-lgu-mabuhay',
                'hero_logo' => '1785834798_about-lgu-mabuhay.png',
                'hero_logo_alt' => 'LGU Mabuhay',
                'hero_title' => 'Municipality of Mabuhay',
                'hero_description' => 'A progressive local government unit committed to transparent, efficient, and citizen-centered governance.',
                'overview_badge' => 'Municipality Overview',
                'overview_title' => 'About Mabuhay',
                'overview_paragraphs' => [
                    'The Municipality of Mabuhay is a 4th class municipality in the province of Zamboanga Sibugay, Philippines. Known for its rich cultural heritage and agricultural community, Mabuhay is committed to progressive governance and sustainable local development.',
                    'The municipal government continues to foster economic growth, improve public education and health services, and strengthen environmental stewardship through responsive, people-centered administration.',
                    'Through digital governance initiatives and coordinated public service delivery, LGU Mabuhay aims to make government services more accessible, transparent, and empowering for every resident.',
                ],
                'overview_highlights' => [
                    'Digital service access and public information support',
                    'Community-based programs for agriculture and livelihoods',
                    'Health, education, and inclusive municipal coordination',
                ],
                'media_badge' => 'Media Feature',
                'media_title' => 'Municipal Video Showcase',
                'media_preview_image' => 'lgu_mabuhay.jpg',
                'media_video' => null,
                'organization_mayor_name' => 'Hon. Edrelusa "Lulu" Calonge',
                'organization_mayor_role' => 'Municipal Mayor',
                'organization_mayor_image' => '1785837572_organization-mayor.png',
                'organization_vice_mayor_name' => 'Hon. Joval John B. Samonte',
                'organization_vice_mayor_role' => 'Municipal Vice Mayor',
                'organization_vice_mayor_image' => '1785840758_organization-vice-mayor.png',
                'organization_council_members' => [
                    ['id' => '1', 'name' => 'Maria Pilar T. Adlaon', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-1.png'],
                    ['id' => '2', 'name' => 'Hon. Majin V. Andak', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-2.png'],
                    ['id' => '3', 'name' => 'Alvarez H. Dammang', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-3.png'],
                    ['id' => '4', 'name' => 'Hon. Alvin D. Hassan', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-4.png'],
                    ['id' => '5', 'name' => 'Hon. Rey T. Omamalin', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-5.png'],
                    ['id' => '6', 'name' => 'Hon. Julhisan "Isan" H. Buhali', 'role' => 'Council Member', 'image' => null],
                    ['id' => '7', 'name' => 'Hon. Bhong Anjawang', 'role' => 'Council Member', 'image' => null],
                    ['id' => '15', 'name' => 'Hon. Dario S. Alforque', 'role' => 'Council Member', 'image' => '1785840758_organization-council-member-8.png'],
                ],
                'lgu_badge' => 'Barangay Reference Collection',
                'lgu_subtitle' => 'Municipal Directory Layout Preview',
                'lgu_title' => 'Municipality of Mabuhay',
                'lgu_logo' => null,
                'lgu_barangays' => $barangays,
                'media_overlay_title' => 'Mabuhay Overview Video',
                'media_overlay_description' => 'Replace this showcase with the official LGU Mabuhay video presentation, tourism reel, or public service introduction when media is ready.',
                'media_footer_left' => 'Video Player Placeholder',
                'media_footer_right' => '16:9 Presentation Area',
                'priorities_title' => 'Governance Priorities',
                'priorities_items' => [],
                'created_at' => '2026-08-04 01:33:24',
                'updated_at' => '2026-08-04 01:59:32',
            ],
        );

        if (Schema::hasTable('about_priorities')) {
            $about->priorities()->delete();
        }

        if (Schema::hasTable('about_barangays') && Schema::hasTable('about_barangay_kagawads')) {
            $about->barangays()->delete();
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function runBarangaySeedData(): array
    {
        return [
            [
                'id' => 1,
                'title' => 'Abunda',
                'reference' => 'BRGY-001',
                'population' => 893,
                'barangayCaptain' => 'Maria Cruz',
                'secretary' => 'Jose Mendoza',
                'treasurer' => 'Michael Torres',
                'skChairperson' => 'Grace Flores',
                'kagawads' => ['Robert Ramos', 'Ana Navarro', 'Mark Diaz', 'Leah Santos', 'Kevin Garcia', 'Joy Reyes', 'Paul Cruz'],
                'contact' => [
                    'mobile' => '09171000001',
                    'telephone' => '(062) 555-1001',
                    'email' => 'brgy001@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Abunda, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.901000000000001,
                    'longitude' => 122.101,
                ],
                'description' => 'Development seed data for Abunda. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 2,
                'title' => 'Bagong Silang (Tumalog)',
                'reference' => 'BRGY-002',
                'population' => 1596,
                'barangayCaptain' => 'Jose Flores',
                'secretary' => 'Michael Ramos',
                'treasurer' => 'Grace Navarro',
                'skChairperson' => 'Robert Diaz',
                'kagawads' => ['Ana Santos', 'Mark Garcia', 'Leah Reyes', 'Kevin Cruz', 'Joy Mendoza', 'Paul Torres', 'Ramon Flores'],
                'contact' => [
                    'mobile' => '09171000002',
                    'telephone' => '(062) 555-1002',
                    'email' => 'brgy002@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Bagong Silang (Tumalog), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.902,
                    'longitude' => 122.10199999999999,
                ],
                'description' => 'Development seed data for Bagong Silang (Tumalog). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 3,
                'title' => 'Bangkaw-bangkaw',
                'reference' => 'BRGY-003',
                'population' => 1750,
                'barangayCaptain' => 'Michael Diaz',
                'secretary' => 'Grace Santos',
                'treasurer' => 'Robert Garcia',
                'skChairperson' => 'Ana Reyes',
                'kagawads' => ['Mark Cruz', 'Leah Mendoza', 'Kevin Torres', 'Joy Flores', 'Paul Ramos', 'Ramon Navarro', 'Sheila Diaz'],
                'contact' => [
                    'mobile' => '09171000003',
                    'telephone' => '(062) 555-1003',
                    'email' => 'brgy003@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Bangkaw-bangkaw, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.9030000000000005,
                    'longitude' => 122.103,
                ],
                'description' => 'Development seed data for Bangkaw-bangkaw. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 4,
                'title' => 'Caliran (Turko)',
                'reference' => 'BRGY-004',
                'population' => 2828,
                'barangayCaptain' => 'Grace Reyes',
                'secretary' => 'Robert Cruz',
                'treasurer' => 'Ana Mendoza',
                'skChairperson' => 'Mark Torres',
                'kagawads' => ['Leah Flores', 'Kevin Ramos', 'Joy Navarro', 'Paul Diaz', 'Ramon Santos', 'Sheila Garcia', 'Dennis Reyes'],
                'contact' => [
                    'mobile' => '09171000004',
                    'telephone' => '(062) 555-1004',
                    'email' => 'brgy004@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Caliran (Turko), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.904,
                    'longitude' => 122.104,
                ],
                'description' => 'Development seed data for Caliran (Turko). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 5,
                'title' => 'Catipan',
                'reference' => 'BRGY-005',
                'population' => 1486,
                'barangayCaptain' => 'Robert Torres',
                'secretary' => 'Ana Flores',
                'treasurer' => 'Mark Ramos',
                'skChairperson' => 'Leah Navarro',
                'kagawads' => ['Kevin Diaz', 'Joy Santos', 'Paul Garcia', 'Ramon Reyes', 'Sheila Cruz', 'Dennis Mendoza', 'Rose Torres'],
                'contact' => [
                    'mobile' => '09171000005',
                    'telephone' => '(062) 555-1005',
                    'email' => 'brgy005@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Catipan, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.905,
                    'longitude' => 122.10499999999999,
                ],
                'description' => 'Development seed data for Catipan. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 6,
                'title' => 'Kauswagan',
                'reference' => 'BRGY-006',
                'population' => 1600,
                'barangayCaptain' => 'Ana Navarro',
                'secretary' => 'Mark Diaz',
                'treasurer' => 'Leah Santos',
                'skChairperson' => 'Kevin Garcia',
                'kagawads' => ['Joy Reyes', 'Paul Cruz', 'Ramon Mendoza', 'Sheila Torres', 'Dennis Flores', 'Rose Ramos', 'Carlo Navarro'],
                'contact' => [
                    'mobile' => '09171000006',
                    'telephone' => '(062) 555-1006',
                    'email' => 'brgy006@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Kauswagan, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.906000000000001,
                    'longitude' => 122.106,
                ],
                'description' => 'Development seed data for Kauswagan. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 7,
                'title' => 'Ligaya',
                'reference' => 'BRGY-007',
                'population' => 1799,
                'barangayCaptain' => 'Mark Garcia',
                'secretary' => 'Leah Reyes',
                'treasurer' => 'Kevin Cruz',
                'skChairperson' => 'Joy Mendoza',
                'kagawads' => ['Paul Torres', 'Ramon Flores', 'Sheila Ramos', 'Dennis Navarro', 'Rose Diaz', 'Carlo Santos', 'Angel Garcia'],
                'contact' => [
                    'mobile' => '09171000007',
                    'telephone' => '(062) 555-1007',
                    'email' => 'brgy007@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Ligaya, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.907,
                    'longitude' => 122.107,
                ],
                'description' => 'Development seed data for Ligaya. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 8,
                'title' => 'Looc-Barlak',
                'reference' => 'BRGY-008',
                'population' => 2297,
                'barangayCaptain' => 'Leah Mendoza',
                'secretary' => 'Kevin Torres',
                'treasurer' => 'Joy Flores',
                'skChairperson' => 'Paul Ramos',
                'kagawads' => ['Ramon Navarro', 'Sheila Diaz', 'Dennis Santos', 'Rose Garcia', 'Carlo Reyes', 'Angel Cruz', 'Juan Mendoza'],
                'contact' => [
                    'mobile' => '09171000008',
                    'telephone' => '(062) 555-1008',
                    'email' => 'brgy008@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Looc-Barlak, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.908,
                    'longitude' => 122.10799999999999,
                ],
                'description' => 'Development seed data for Looc-Barlak. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 9,
                'title' => 'Malinao (Sagasa)',
                'reference' => 'BRGY-009',
                'population' => 3788,
                'barangayCaptain' => 'Kevin Ramos',
                'secretary' => 'Joy Navarro',
                'treasurer' => 'Paul Diaz',
                'skChairperson' => 'Ramon Santos',
                'kagawads' => ['Sheila Garcia', 'Dennis Reyes', 'Rose Cruz', 'Carlo Mendoza', 'Angel Torres', 'Juan Flores', 'Maria Ramos'],
                'contact' => [
                    'mobile' => '09171000009',
                    'telephone' => '(062) 555-1009',
                    'email' => 'brgy009@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Malinao (Sagasa), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.909000000000001,
                    'longitude' => 122.109,
                ],
                'description' => 'Development seed data for Malinao (Sagasa). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 10,
                'title' => 'Pamansaan',
                'reference' => 'BRGY-010',
                'population' => 1155,
                'barangayCaptain' => 'Joy Santos',
                'secretary' => 'Paul Garcia',
                'treasurer' => 'Ramon Reyes',
                'skChairperson' => 'Sheila Cruz',
                'kagawads' => ['Dennis Mendoza', 'Rose Torres', 'Carlo Flores', 'Angel Ramos', 'Juan Navarro', 'Maria Diaz', 'Jose Santos'],
                'contact' => [
                    'mobile' => '09171000010',
                    'telephone' => '(062) 555-1010',
                    'email' => 'brgy010@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Pamansaan, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.91,
                    'longitude' => 122.11,
                ],
                'description' => 'Development seed data for Pamansaan. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 11,
                'title' => 'Pinalim (San Roque)',
                'reference' => 'BRGY-011',
                'population' => 1573,
                'barangayCaptain' => 'Paul Cruz',
                'secretary' => 'Ramon Mendoza',
                'treasurer' => 'Sheila Torres',
                'skChairperson' => 'Dennis Flores',
                'kagawads' => ['Rose Ramos', 'Carlo Navarro', 'Angel Diaz', 'Juan Santos', 'Maria Garcia', 'Jose Reyes', 'Michael Cruz'],
                'contact' => [
                    'mobile' => '09171000011',
                    'telephone' => '(062) 555-1011',
                    'email' => 'brgy011@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Pinalim (San Roque), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.9110000000000005,
                    'longitude' => 122.11099999999999,
                ],
                'description' => 'Development seed data for Pinalim (San Roque). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 12,
                'title' => 'Poblacion (Mabuhay)',
                'reference' => 'BRGY-012',
                'population' => 4765,
                'barangayCaptain' => 'Ramon Flores',
                'secretary' => 'Sheila Ramos',
                'treasurer' => 'Dennis Navarro',
                'skChairperson' => 'Rose Diaz',
                'kagawads' => ['Carlo Santos', 'Angel Garcia', 'Juan Reyes', 'Maria Cruz', 'Jose Mendoza', 'Michael Torres', 'Grace Flores'],
                'contact' => [
                    'mobile' => '09171000012',
                    'telephone' => '(062) 555-1012',
                    'email' => 'brgy012@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Poblacion (Mabuhay), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.912,
                    'longitude' => 122.112,
                ],
                'description' => 'Development seed data for Poblacion (Mabuhay). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 13,
                'title' => 'Punawan',
                'reference' => 'BRGY-013',
                'population' => 1466,
                'barangayCaptain' => 'Sheila Diaz',
                'secretary' => 'Dennis Santos',
                'treasurer' => 'Rose Garcia',
                'skChairperson' => 'Carlo Reyes',
                'kagawads' => ['Angel Cruz', 'Juan Mendoza', 'Maria Torres', 'Jose Flores', 'Michael Ramos', 'Grace Navarro', 'Robert Diaz'],
                'contact' => [
                    'mobile' => '09171000013',
                    'telephone' => '(062) 555-1013',
                    'email' => 'brgy013@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Punawan, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.913,
                    'longitude' => 122.113,
                ],
                'description' => 'Development seed data for Punawan. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 14,
                'title' => 'Santo Nino (Caliran)',
                'reference' => 'BRGY-014',
                'population' => 1321,
                'barangayCaptain' => 'Dennis Reyes',
                'secretary' => 'Rose Cruz',
                'treasurer' => 'Carlo Mendoza',
                'skChairperson' => 'Angel Torres',
                'kagawads' => ['Juan Flores', 'Maria Ramos', 'Jose Navarro', 'Michael Diaz', 'Grace Santos', 'Robert Garcia', 'Ana Reyes'],
                'contact' => [
                    'mobile' => '09171000014',
                    'telephone' => '(062) 555-1014',
                    'email' => 'brgy014@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Santo Nino (Caliran), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.914000000000001,
                    'longitude' => 122.11399999999999,
                ],
                'description' => 'Development seed data for Santo Nino (Caliran). Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 15,
                'title' => 'Sawa',
                'reference' => 'BRGY-015',
                'population' => 3027,
                'barangayCaptain' => 'Rose Torres',
                'secretary' => 'Carlo Flores',
                'treasurer' => 'Angel Ramos',
                'skChairperson' => 'Juan Navarro',
                'kagawads' => ['Maria Diaz', 'Jose Santos', 'Michael Garcia', 'Grace Reyes', 'Robert Cruz', 'Ana Mendoza', 'Mark Torres'],
                'contact' => [
                    'mobile' => '09171000015',
                    'telephone' => '(062) 555-1015',
                    'email' => 'brgy015@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Sawa, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.915,
                    'longitude' => 122.115,
                ],
                'description' => 'Development seed data for Sawa. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 16,
                'title' => 'Sioton',
                'reference' => 'BRGY-016',
                'population' => 842,
                'barangayCaptain' => 'Carlo Navarro',
                'secretary' => 'Angel Diaz',
                'treasurer' => 'Juan Santos',
                'skChairperson' => 'Maria Garcia',
                'kagawads' => ['Jose Reyes', 'Michael Cruz', 'Grace Mendoza', 'Robert Torres', 'Ana Flores', 'Mark Ramos', 'Leah Navarro'],
                'contact' => [
                    'mobile' => '09171000016',
                    'telephone' => '(062) 555-1016',
                    'email' => 'brgy016@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Sioton, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.916,
                    'longitude' => 122.116,
                ],
                'description' => 'Development seed data for Sioton. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 17,
                'title' => 'Taguisian',
                'reference' => 'BRGY-017',
                'population' => 3778,
                'barangayCaptain' => 'Angel Garcia',
                'secretary' => 'Juan Reyes',
                'treasurer' => 'Maria Cruz',
                'skChairperson' => 'Jose Mendoza',
                'kagawads' => ['Michael Torres', 'Grace Flores', 'Robert Ramos', 'Ana Navarro', 'Mark Diaz', 'Leah Santos', 'Kevin Garcia'],
                'contact' => [
                    'mobile' => '09171000017',
                    'telephone' => '(062) 555-1017',
                    'email' => 'brgy017@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Taguisian, Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.917000000000001,
                    'longitude' => 122.11699999999999,
                ],
                'description' => 'Development seed data for Taguisian. Placeholder officials; replace with verified data.',
            ],
            [
                'id' => 18,
                'title' => 'Tandu-Comot (Katipunan)',
                'reference' => 'BRGY-018',
                'population' => 1426,
                'barangayCaptain' => 'Juan Mendoza',
                'secretary' => 'Maria Torres',
                'treasurer' => 'Jose Flores',
                'skChairperson' => 'Michael Ramos',
                'kagawads' => ['Grace Navarro', 'Robert Diaz', 'Ana Santos', 'Mark Garcia', 'Leah Reyes', 'Kevin Cruz', 'Joy Mendoza'],
                'contact' => [
                    'mobile' => '09171000018',
                    'telephone' => '(062) 555-1018',
                    'email' => 'brgy018@example.gov.ph',
                ],
                'address' => 'Barangay Hall, Tandu-Comot (Katipunan), Mabuhay, Zamboanga Sibugay',
                'officeHours' => 'Monday-Friday, 8:00 AM - 5:00 PM',
                'puroks' => ['Purok 1', 'Purok 2', 'Purok 3', 'Purok 4'],
                'facilities' => ['Barangay Hall', 'Health Station', 'Day Care Center', 'Covered Court'],
                'schools' => ['Elementary School'],
                'healthFacilities' => ['Barangay Health Station'],
                'evacuationCenters' => ['Barangay Covered Court'],
                'emergency' => [
                    'police' => '911',
                    'fire' => '911',
                    'ambulance' => '911',
                ],
                'coordinates' => [
                    'latitude' => 7.918,
                    'longitude' => 122.118,
                ],
                'description' => 'Development seed data for Tandu-Comot (Katipunan). Placeholder officials; replace with verified data.',
            ],
        ];
    }
}
