<?php

namespace Database\Seeders;

use App\Models\DostServiceContent;
use Illuminate\Database\Seeder;

class DostServiceContentSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            0 => [
                'id' => 1,
                'tab_id' => 'ProgramsServices',
                'title' => 'SMART AND SUSTAINABLE COMMUNITIES PROGRAM',
                'slug' => 'smart-and-sustainable-communities-program',
                'description' => 'SMARTER, SUSTAINABLE, RESILIENT AND INCLUSIVE COMMUNITIES THROUGH SCIENCE TECHNOLOGY AND INNOVATION (STI)',
                'image' => '1788620191_smart-and-sustainable-communities-program.png',
                'pdf' => '1788620191_smart-and-sustainable-communities-program.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 14:56:31',
                'updated_at' => '2026-09-05 14:56:31',
            ],
            1 => [
                'id' => 2,
                'tab_id' => 'ProgramsServices',
                'title' => 'DOST Scholarship Program',
                'slug' => 'dost-scholarship-program',
                'description' => 'S&T Undergraduate and Junior Level Science Scholarship (JLSS)',
                'image' => '1788620371_dost-scholarship-program.png',
                'pdf' => '1788620371_dost-scholarship-program.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 14:59:31',
                'updated_at' => '2026-09-05 14:59:31',
            ],
            2 => [
                'id' => 3,
                'tab_id' => 'ProgramsServices',
                'title' => 'DOST IX Local Grants-in-Aid (GIA) Program',
                'slug' => 'dost-ix-local-grants-in-aid-gia-program',
                'description' => 'Aims to harness the country’s scientific and technological capabilities to spur and attain sustainable economic growth and development.',
                'image' => '1788621290_dost-ix-local-grants-in-aid-gia-program.png',
                'pdf' => '1788621291_dost-ix-local-grants-in-aid-gia-program.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 15:14:51',
                'updated_at' => '2026-09-05 15:14:51',
            ],
            3 => [
                'id' => 4,
                'tab_id' => 'ProgramsServices',
                'title' => 'Small Enterprise Technology Upgrading Program (SETUP)',
                'slug' => 'small-enterprise-technology-upgrading-program-setup',
                'description' => 'SETUP provides assistance to Micro, Small, and Medium Enterprises (MSMEs) that will enable them to enhance their businesses.',
                'image' => '1788621709_small-enterprise-technology-upgrading-program-setup.png',
                'pdf' => '1788621709_small-enterprise-technology-upgrading-program-setup.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 15:21:49',
                'updated_at' => '2026-09-05 15:21:49',
            ],
            4 => [
                'id' => 5,
                'tab_id' => 'ProgramsServices',
                'title' => 'DOST iFWD PH Program',
                'slug' => 'dost-ifwd-ph-program',
                'description' => 'Provide support opportunities for OFWs and their immediate families to establish technology-based enterprises in the country.',
                'image' => '1788622576_dost-ifwd-ph-program.png',
                'pdf' => '1788622576_dost-ifwd-ph-program.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 15:36:16',
                'updated_at' => '2026-09-05 15:36:16',
            ],
            5 => [
                'id' => 6,
                'tab_id' => 'ProgramsServices',
                'title' => 'RSTL - Regional Standards and Testing Laboratories',
                'slug' => 'rstl-regional-standards-and-testing-laboratories',
                'description' => 'RSTL - Regional Standards and Testing Laboratories',
                'image' => '1788623096_rstl-regional-standards-and-testing-laboratories.png',
                'pdf' => '1788623096_rstl-regional-standards-and-testing-laboratories.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 15:44:56',
                'updated_at' => '2026-09-05 15:44:56',
            ],
            6 => [
                'id' => 7,
                'tab_id' => 'FacebookPosts',
                'title' => 'MOA signing of newly-approved CEST-Mabuhay Project',
                'slug' => 'moa-signing-of-newly-approved-cest-mabuhay-project',
                'description' => 'The LGU was granted with the assistance amounting to ₱2,469,060.00 that will address the challenges/issues of the Municipality in terms of environment, education, technology and economic livelihood.',
                'image' => '1788623594_moa-signing-of-newly-approved-cest-mabuhay-project.jpg',
                'pdf' => '1788623651_moa-signing-of-newly-approved-cest-mabuhay-project.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 15:53:14',
                'updated_at' => '2026-09-05 15:54:11',
            ],
            7 => [
                'id' => 8,
                'tab_id' => 'FacebookPosts',
                'title' => 'Ceremonial Turnover of CEST Funding Assistance',
                'slug' => 'ceremonial-turnover-of-cest-funding-assistance',
                'description' => 'Municipal Mayor Edreluisa O. Caloñge leads the acceptance of fund assistance granted by the Department of Science and Technology Office No. IX (DOST-IX) through its Provincial Science and Technology Office of Zamboanga Sibugay Province (PSTO-ZSP) during the 57th Araw ng Mabuhay Celebration in Mabuhay, Zamboanga Sibugay Province.',
                'image' => '1788624217_ceremonial-turnover-of-cest-funding-assistance.jpg',
                'pdf' => '1788624217_ceremonial-turnover-of-cest-funding-assistance.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 16:03:37',
                'updated_at' => '2026-09-05 16:03:37',
            ],
            8 => [
                'id' => 9,
                'tab_id' => 'FacebookPosts',
                'title' => 'Turnover of the 1st Community Tsunami Alerting Station (CTAS) in the Zamboanga Sibugay Province to the LGU-Mabuhay',
                'slug' => 'turnover-of-the-1st-community-tsunami-alerting-station-ctas-in-the-zamboanga-sibugay-province-to-the-lgu-mabuhay',
                'description' => 'DOST IX Turns Over First Community Tsunami Alerting Station in Zamboanga Sibugay',
                'image' => '1788624386_turnover-of-the-1st-community-tsunami-alerting-station-ctas-in-the-zamboanga-sibugay-province-to-the-lgu-mabuhay.jpg',
                'pdf' => '1788624386_turnover-of-the-1st-community-tsunami-alerting-station-ctas-in-the-zamboanga-sibugay-province-to-the-lgu-mabuhay.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 16:06:26',
                'updated_at' => '2026-09-05 17:22:15',
            ],
            9 => [
                'id' => 10,
                'tab_id' => 'FacebookPosts',
                'title' => 'DOST IX Turns Over 8 STARBOOKS Units in Zamboanga Sibugay',
                'slug' => 'dost-ix-turns-over-8-starbooks-units-in-zamboanga-sibugay',
                'description' => 'The DOST Regional Office No. IX, through its Provincial Science and Technology Office of Zamboanga Sibugay (PSTO-ZSP), successfully turned over eight (08) units of STARBOOKS to the beneficiary schools in the municipalities of Alicia and Mabuhay, Zamboanga Sibugay,',
                'image' => '1788624562_dost-ix-turns-over-8-starbooks-units-in-zamboanga-sibugay.jpg',
                'pdf' => '1788624562_dost-ix-turns-over-8-starbooks-units-in-zamboanga-sibugay.pdf',
                'video' => null,
                'is_active' => 1,
                'created_at' => '2026-09-05 16:09:22',
                'updated_at' => '2026-09-05 16:09:22',
            ],
        ];

        DostServiceContent::query()->upsert($rows, ['id']);
    }
}
